// ==============================================
// AyuLink Patient - Medication Reminders
// Schedules one repeating local notification per dose time, for
// each dispensed medication, until its course finishes.
//
// These are LOCAL notifications, not push: expo-notifications hands
// them to the OS scheduler (iOS UNUserNotificationCenter / Android
// AlarmManager), which delivers them even when the app is closed or
// killed. Nothing server-side has to stay awake, and they keep working
// with no network.
// ==============================================

import * as Notifications from "expo-notifications";
import AsyncStorage from "@react-native-async-storage/async-storage";

/** Dose times we map a frequency onto, in 24h local time. */
const DOSE_TIMES: Record<string, number[]> = {
    once: [9],
    twice: [9, 21],
    three: [8, 14, 20],
    four: [8, 12, 16, 20],
};

export interface ReminderDrug {
    drugName: string;
    dosage?: string | null;
    frequency?: string | null;
    duration?: string | null;
    route?: string | null;
    instructions?: string | null;
    durationDays?: number | null;
    dispensedAt?: string | null;
}

/**
 * Dose hours for a free-text frequency ("Twice daily", "Every 8 hours",
 * "As needed"). Returns [] when there is no fixed schedule to remind
 * against — "as needed" medication shouldn't nag someone on a timer.
 */
export function doseHoursFor(frequency: string | null | undefined): number[] {
    const f = (frequency ?? "").toLowerCase().trim();
    if (!f) return DOSE_TIMES.once;
    if (f.includes("as needed") || f.includes("prn") || f.includes("when required")) return [];

    if (f.includes("once") || f.includes("1 time") || f.includes("od")) return DOSE_TIMES.once;
    if (f.includes("twice") || f.includes("2 time") || f.includes("bd")) return DOSE_TIMES.twice;
    if (f.includes("three") || f.includes("3 time") || f.includes("tds") || f.includes("tid"))
        return DOSE_TIMES.three;
    if (f.includes("four") || f.includes("4 time") || f.includes("qds") || f.includes("qid"))
        return DOSE_TIMES.four;

    // "Every N hours" -> spread N-hourly across waking hours.
    const everyHours = f.match(/every\s+(\d+)\s*h/);
    if (everyHours) {
        const step = Math.max(1, Number(everyHours[1]));
        const hours: number[] = [];
        for (let h = 8; h < 22; h += step) hours.push(h);
        return hours.length ? hours : DOSE_TIMES.once;
    }

    return DOSE_TIMES.once;
}

const STORAGE_KEY = (treatmentId: string) => `ayulink.reminders.${treatmentId}`;

/**
 * Schedule daily reminders for every dispensed drug that has a fixed
 * schedule, and one notification at the end of the whole course.
 *
 * `message` for each drug is supplied by the caller (generated by the
 * assistant, so the wording is natural and in the patient's language) —
 * this module only handles the scheduling.
 */
export async function scheduleCourseReminders(
    treatmentId: string,
    drugs: ReminderDrug[],
    messages: Record<string, string>,
    courseEndsAt: string | null
): Promise<number> {
    const { status } = await Notifications.getPermissionsAsync();
    let granted = status === "granted";
    if (!granted) {
        granted = (await Notifications.requestPermissionsAsync()).status === "granted";
    }
    if (!granted) return 0;

    // Replace rather than stack: re-running this for the same treatment
    // must not leave the previous batch firing as well.
    await cancelCourseReminders(treatmentId);

    const ids: string[] = [];

    for (const drug of drugs) {
        const hours = doseHoursFor(drug.frequency);
        if (hours.length === 0) continue;

        const body =
            messages[drug.drugName] ??
            [drug.dosage, drug.frequency].filter(Boolean).join(" · ") ??
            "Time for your medication";

        for (const hour of hours) {
            const id = await Notifications.scheduleNotificationAsync({
                content: {
                    title: `Time for ${drug.drugName}`,
                    body,
                    data: { treatmentId, drugName: drug.drugName, kind: "medication" },
                },
                trigger: {
                    type: Notifications.SchedulableTriggerInputTypes.DAILY,
                    hour,
                    minute: 0,
                },
            });
            ids.push(id);
        }
    }

    // The end-of-course check-in. Tapping this opens the app and starts
    // the "how are you feeling now?" conversation.
    if (courseEndsAt) {
        const endsAt = new Date(courseEndsAt);
        if (endsAt.getTime() > Date.now()) {
            const id = await Notifications.scheduleNotificationAsync({
                content: {
                    title: "How are you feeling?",
                    body: "You should have finished your medication — tap to let your assistant know how it went.",
                    data: { treatmentId, kind: "course_end" },
                },
                trigger: {
                    type: Notifications.SchedulableTriggerInputTypes.DATE,
                    date: endsAt,
                },
            });
            ids.push(id);
        }
    }

    await AsyncStorage.setItem(STORAGE_KEY(treatmentId), JSON.stringify(ids));
    return ids.length;
}

export async function cancelCourseReminders(treatmentId: string): Promise<void> {
    try {
        const raw = await AsyncStorage.getItem(STORAGE_KEY(treatmentId));
        if (!raw) return;
        const ids: string[] = JSON.parse(raw);
        await Promise.all(
            ids.map((id) => Notifications.cancelScheduledNotificationAsync(id).catch(() => {}))
        );
        await AsyncStorage.removeItem(STORAGE_KEY(treatmentId));
    } catch {
        // Nothing scheduled, or storage unavailable — nothing to undo.
    }
}

export async function hasCourseReminders(treatmentId: string): Promise<boolean> {
    try {
        const raw = await AsyncStorage.getItem(STORAGE_KEY(treatmentId));
        return !!raw && JSON.parse(raw).length > 0;
    } catch {
        return false;
    }
}
